# Generated by Django 4.2.3 on 2024-08-29 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_task_deleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='testdesc',
            new_name='teskdesc',
        ),
    ]
